# SPDX-FileCopyrightText: 2025 BrainCraft.io
# SPDX-License-Identifier: Apache-2.0

name: Markdown Link Check

# This workflow validates all markdown links in the repository
# It checks for broken internal links, anchors, and external URLs

on:
  # Direct triggers for this repository
  push:
    branches: [main, master]
    paths:
      - '**.md'
      - '.github/workflows/markdown-link-check.yml'
  pull_request:
    branches: [main, master]
    paths:
      - '**.md'
      - '.github/workflows/markdown-link-check.yml'
  
  # Manual trigger
  workflow_dispatch:
  
  # Scheduled check (weekly on Sundays)
  schedule:
    - cron: '0 0 * * 0'

jobs:
  check-links:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Need full history for checking branch references
          fetch-depth: 0

      - name: Run Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          # Check all markdown files
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          
          # Configuration file (if exists)
          config-file: '.markdown-link-check.json'
          
          # Check modified files in PRs
          check-modified-files-only: 'no'
          
          # Base branch for comparison
          base-branch: 'main'
          
          # File path pattern
          file-path: './'
          
          # File extension to check
          file-extension: '.md'
          
          # Maximum number of retries for external links
          max-depth: 3

      - name: Upload Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: broken-links-report
          path: |
            **/*-markdown-link-check.log
          retention-days: 7

      - name: Comment PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `
            ❌ **Markdown Link Check Failed**
            
            Some links in your markdown files are broken. Please check the logs for details.
            
            To run this check locally:
            \`\`\`bash
            npm install -g markdown-link-check
            find . -name "*.md" -exec markdown-link-check {} \;
            \`\`\`
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

# Usage Notes:
# 
# This workflow helps maintain documentation quality by checking:
# - Internal file references (relative paths)
# - Anchor links within documents
# - External URLs (with retry logic for transient failures)
#
# To exclude certain URLs or patterns, create a .markdown-link-check.json file:
# {
#   "ignorePatterns": [
#     { "pattern": "^http://localhost" },
#     { "pattern": "^https://example.com" }
#   ],
#   "timeout": "20s",
#   "retryOn429": true,
#   "retryCount": 3,
#   "fallbackRetryDelay": "30s"
# }